### ISSUE TITLE
Convert existing wolfpackbot commands to insert statements

### ISSUE THREAD

**Issue by wlvstv** [wlvstv/wopo#1]
We need to convert all those existing commands found in the [wolfpackbot](https://github.com/wlvstv/wolfpackbot/blob/master/wolvesatmydoor.ini) into insert statements to put into the new bot's database. We just want the non-mod (public) commands for now and we don't want anything that has any logic to it (counters) the format should look like this:

`INSERT INTO public.commands(command, isMod, response, creator, channel) VALUES (<command>, false, <command response>, 'wopo', 'wolvesatmydoor')`

**Comment by BenKaiser12** [comment]
Attached is a .txt file with each line containing an INSERT statement for the old public wolfpackbot commands.  

[inserts.txt](https://github.com/wlvstv/wopo/files/1715096/inserts.txt)

**Comment by wlvstv** [comment]
Thanks Ben! 👍
