### ISSUE TITLE
Add a "Single Stream Dinner-Record" command that can be updated via a mod command in chat

### ISSUE THREAD

**Issue by Sparkplug1034** [wlvstv/wopo#2]
i.e. _(mod only)_ !winrecord 12 

WolfpackBot: Dinner-record updated

_(anyone)_ !winrecord 

WolfpackBot: The most dinners in a single stream is 12, achieved on 2/9/18! The previous record was 7.

**Comment by wlvstv** [comment]
Do we think we need the previous record? it would change how we would track this in the database...

**Comment by Sparkplug1034** [comment]
I don't think we need it but I don't think it would take much. Just a static variable that get's updated with the current previous record, when a new record is set. If that makes sense.
