### ISSUE TITLE
!cycle

### ISSUE THREAD

**Issue by Aaron7897** [wlvstv/wopo#42]
Format: !cycle <command> or !cycle <stop>

Description: Will post whatever command you choose every "X" minutes. For example !cycle !app would display the app commands message every few minutes (we could set it to a custom amount of time too I guess !cycle <command> <minutes>). The "!cycle stop" will stop the cycle. Not sure if we should let multiple cycles go at once though

**Comment by DerekNMartin** [comment]
Can I get permission to submit a merge request? I've got this one complete.

**Comment by DerekNMartin** [comment]
Thanks! I've sent in a MR for review.
My name on twitch is derekmartian :)
