### ISSUE TITLE
Bot Web Interface

### ISSUE THREAD

**Issue by BenKaiser12** [wlvstv/wopo#9]
This might be thinking ahead a little, but do we want to write a web interface for command management?  Something mods can login to and manage things with?  I picture a webpage that will pull from the database providing CRUD tools for command management.  it might also be a good way to edit things like usernames and records and such outside of chat if need be.  It's just an idea...let me know what y'all think!

**Comment by Sparkplug1034** [comment]
Would this be really easy if it can be accessed on the same AWS instance/whatever as wopo? Then it could have passthrough page that authenticates by username and password (or even better.... twitch account authentication) and redirects to a simple single html/css UI page that uses a script to update database values, and then a "command line" that could effectively act as a chat-channel for mods to add/modidy/delete commands.

**Comment by BenKaiser12** [comment]
Im going to take a crack at getting a base page setup.  I have been thinking about it all day and it seems like a good weekend project :-)

**Comment by wlvstv** [comment]
what are you thinking in terms of web tech?

**Comment by BenKaiser12** [comment]
I was thinking a simple express app with some bootstrap styling.  I am familiar with using ejs for templates so I was going to use that.

**Comment by wlvstv** [comment]
ok cool,that sounds good! I was going to suggest against doing anything too crazy like react or vue
